# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-31 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('funcion_nombre', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calculo', models.DecimalField(decimal_places=100, max_digits=100)),
                ('intervalo', models.DecimalField(decimal_places=3, max_digits=100)),
                ('numero_trapecios', models.IntegerField(default=0)),
            ],
        ),
    ]
